### ISSUE TITLE
Question: Fuzzy hash format

### ISSUE THREAD

**Issue by localacct** [ssdeep-project/ssdeep#23]
Hi

When I compute a fuzzy hash for a file, I will see the output such as the following
````
48:<rest of fuzzy hash>
````
Where there is a number at the front of the hash. What does the number at the front mean? Is it part of the fuzzy hash?

**Comment by a4lg** [comment]
ssdeep is based on Context Triggered Piecewise Hashing (CTPH).

What ssdeep does is, roughly to say, split the file to smaller blocks based on the ”context” (last few bytes from the ”block”) and concatenate hashes from each block (single Base64 character in ssdeep).
ssdeep chooses optimal ”average probability of splitting the block” (reciprocal of what we call ”block size”) based on the file size and actual contents and 48 means **first block hash** is generated by splitting the file with average probability of 1/48 per byte.

As I said **first**, you actually see is formatted like this:

```
48:<first block hash with block size 48>:<second block hash with block size 48*2 == 96>
```

Yes, 48 is a part of the fuzzy hash. In general, this block size field is `3 * 2^n (0 <= n <= 30)`.

The reason of this is because we can only compare similarity of two block hashes with **the same block size**.

```
Case 1:
48:AAA:BBB
96:    CCC:DDD
       ===
       block hashes (BBB and CCC) are compared
       (BBB and CCC are block hashes with the same block size, 96)

Case 2:
48:AAA:BBB
48:CCC:DDD
   === ===
   two pairs of block hashes (AAA and CCC / BBB and DDD)
   are compared and the final similarity score is basically:
     max(score("AAA","CCC",48), score("BBB","DDD",96))

Case 3:
24:AAA:BBB
96:CCC:DDD
   we cannot compare them because there's no block hashes
   with the same block size. the final score is zero.
```

Because of this, block size field (48 in this case) is absolutely necessary.
