### ISSUE TITLE
License Type Clarification - GPL 2 or Later

### ISSUE THREAD

**Issue by k-glynn** [ssdeep-project/ssdeep#26]
Hi all, 

This component is listed as GPL 2 in the license file. Some of the headers state 'GPL 2 or later', however Main.cpp states that it is licensed as GPL 2 only. 

Would it be possible to correct all headers to 'GPL 2 or later'?

Additionally, ssdeep.h contains a Facebook copyright. Facebook does not normally license any of their code under the GPL. Please could you confirm there is not a missing Facebook license in the header?

Thank you.

**Comment by a4lg** [comment]
Hi,

(a) From my understanding, Facebook copyright is okay because the original author, Mr. Jesse Kornblum, is a Facebook employee.
(b) While not impossible, it's not easy to relicense all components with "GPLv2 or later" because changing license requires nearly all comtributors' permission (portion I wrote could be relicensed even with terms of the MIT license ... but my portion is not big enough).

I understand that I haven't fully answered your questions yet, so feel free to re-open this issue if you have any questions.
